// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB29XlxPppEHP1lRO0g8MjCwm_fQMkRK8k',
    appId: '1:1093941954284:web:1bc649e5d5896ac60c87c9',
    messagingSenderId: '1093941954284',
    projectId: 'ecommerce-ng-57ad9',
    authDomain: 'ecommerce-ng-57ad9.firebaseapp.com',
    storageBucket: 'ecommerce-ng-57ad9.appspot.com',
    measurementId: 'G-SK46Q318KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD-GJHdWXuSMa2IvTylXPp5R7uizcPh4Y',
    appId: '1:1093941954284:android:ac9e40fc46839bc00c87c9',
    messagingSenderId: '1093941954284',
    projectId: 'ecommerce-ng-57ad9',
    storageBucket: 'ecommerce-ng-57ad9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfCqcuw8tI0Ntzu4RtZOfEtqxuuvt63Xs',
    appId: '1:1093941954284:ios:8a9b11305c7e52530c87c9',
    messagingSenderId: '1093941954284',
    projectId: 'ecommerce-ng-57ad9',
    storageBucket: 'ecommerce-ng-57ad9.appspot.com',
    iosClientId: '1093941954284-00mg78htra8vi3s3lt2tot8etb5vk1us.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceNd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfCqcuw8tI0Ntzu4RtZOfEtqxuuvt63Xs',
    appId: '1:1093941954284:ios:a364c01d1c061f080c87c9',
    messagingSenderId: '1093941954284',
    projectId: 'ecommerce-ng-57ad9',
    storageBucket: 'ecommerce-ng-57ad9.appspot.com',
    iosClientId: '1093941954284-iscnpe0pds1ocjb71vams0399tp58rua.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceNd.RunnerTests',
  );
}
